### PR TITLE
Healthsystem to Dev Merge

### PR DESCRIPTION
**Pull request by NomadNiko**
You can checkout my code and play the boss fight, things are pretty stable and just need others to add more and help iron out some things.

### CODE REVIEW

**Comment by MattiGen** [comment]
resolved a handful on merge conflicts on your branch, mostly seemed to be unity not knowing how to handle some things that were evidently not conflicts. In doing that I broke the pan slam animation but as I need to redo it anyway I'm not concerned. Feel free to merge once you've just opened the branch and ensured it doesnt need to open in safe mode

**Comment by MattiGen** [comment]
the boss seems to not take damage, I'm not sure if that has been added yet. I think it's due to in HitBoxAttack the health cariable you're assigning belongs to the player, not the boss

**Comment by MattiGen** [comment]
Why is the player dying here? Looks to be related to the pan slam. (Video in thread in discord). Seems you're not actually checking for collision with the pan, just making it do damage. The pan has the same hitbox script associated with it as the firework

**Comment by MattiGen** [comment]
But nothing in this PR breaks anything, so if it's easier to fix these issues after merge then feel free to merge and we can adjust later

**Comment by MattiGen** [comment]
Fixed the pan animation now somehow. All my above comments still stand though

**Comment by NomadNiko** [comment]
Yeah I'm going to pull that out, the pan attack wasnt doing any damage and I was working on the UI and needed to be losing health.  Will take that back out and merge.

**Pull request merged**
